# Site settings
title: Todd Ekenstam
url: "http://ekenstam.github.io"
baseurl: ""
description: >
  Todd Ekenstam's blog on software development and quality engineering.

# Your information
#email: todd_ekenstam at intuit.com
author: Todd Ekenstam
avatar: "//www.gravatar.com/avatar/40fa67613bdf295e20afb402dca91739?d=mm&s=135"
profile: Todd is a software engineer at Intuit working on improving the quality of web services and web applications with a focus on web services, test automation, continuous integration/deployment and cloud computing.
#twitter_username: twitter_username
github_username: ekenstam
linkedin_username: tekenstam

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /blog/:year-:month-:day/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
