# Site settings
title: Todd Ekenstam
url: "http://ekenstam.github.io"
baseurl: ""
description: >
  One or more sentences introducing this blog.

# Your information
email: todd_ekenstam@intuit.com
#email: tekenstam@gmail.com
author: Todd Ekenstam
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: One sentence introducing yourself.
#twitter_username: twitter_username
github_username: ekenstam

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
